apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: demo-marvel-app
build:
  artifacts:
  - image: vfiftyfive/flask_marvel
    context: app
    custom:
      buildCommand: sh ../build.sh
  - image: vfiftyfive/marvel_init_db
    context: marvel_init_db
    custom:
      buildCommand: sh ../build.sh
  local:
    push: true
deploy:
  kustomize:
    paths: 
    - "/Users/nvermande/Documents/Dev/CFD/app_manifests/overlay/dev"
    
