apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: demo-marvel-app
build:
  artifacts:
  - image: vfiftyfive/flask_marvel
    context: app
    custom:
      buildCommand: sh ../build.sh
  - image: vfiftyfive/marvel_init_db
    context: marvel_init_db
    custom:
      buildCommand: sh ../build.sh
  local:
    push: true
cluster:
  - namespace: dev
deploy:
  kustomize:
    paths: 
    - "/Users/nvermande/Documents/Dev/Ondat/CFD/app_manifests/overlay/dev"
    
